### ISSUE TITLE
"process" substitution executes command immediately after substitution

### ISSUE THREAD

**Issue by jontroncoso** [villfa/composer-substitution-plugin#10]
The command is getting executed before continuing after the substitution. So, if you use the substitution in the middle and have other options after the substitution, the post-substitution options/flags/arguments won't be read.

```
// composer.json
{
  "scripts": {
    "bash": [
      "docker exec -ti {CONTAINER} bash"
    ]
  },
    "substitution": {
      "enable": true,
      "mapping": {
        "{CONTAINER}": {
          "type": "process",
          "value": "docker ps -aqf ancestor=special-tag"
        }
      }
    }
}
```
results in 
```
ivr (git)-[1337-ivr-tests]- % composer bash
> docker exec -ti ae055d08efb2
 bash
"docker exec" requires at least 2 arguments.
See 'docker exec --help'.

Usage:  docker exec [OPTIONS] CONTAINER COMMAND [ARG...]
```

**Comment by villfa** [comment]
I see there is a line break in your command (between the container id and `bash`):
```
> docker exec -ti ae055d08efb2
 bash
```
It probably comes from `docker ps`.

You can trim the command result this way:
```json
    "substitution": {
      "enable": true,
      "mapping": {
        "{CONTAINER}": {
          "type": "process",
          "value": "docker ps -aqf ancestor=special-tag",
          "escape": "trim"
        }
      }
    }
```

**Comment by jontroncoso** [comment]
@villfa Thank you so much. This resolved this specific issue. However now I have a new issue (which i'm sure is unrelated):

```
ivr (git)-[DDA-629-IVR-account-balances]- % composer bash
> docker exec -ti 95bf3fa16ef9 bash
the input device is not a TTY
Script docker exec -ti 95bf3fa16ef9 bash handling the bash event returned with error code 1
```

[This appears to be a limitation with composer itself though](https://stackoverflow.com/questions/43099116/error-the-input-device-is-not-a-tty). Thanks again!

**Comment by villfa** [comment]
You could try adding ` < /dev/tty` to your script:
```
"scripts": {
    "bash": [
        "docker exec -ti {CONTAINER} bash < /dev/tty"
    ]
}
```
Meanwhile I close this issue since your first problem seems fixed.
